email = "notify@me.com"
attempts = 2

[services]

[services."go.dev"]
endpoint = "https://go.dev/"
codes = [200]
timeout = "3s"

[services."debian.org"]
endpoint = "https://debian.org"
codes = [200, 204]
timeout = "5s"
